### PR TITLE
Handle different number of availablity zones and different cloud envi…

### PR DESCRIPTION
**Pull request by akrzos**
…ronments for scaling a cluster up or down

### CODE REVIEW

**Comment by akrzos** [comment]
Please test on GCP @chaitanyaenr , I can test on azure and aws.  Next we will convert this same logic for the workload it self in the workloads repo.

**Comment by chaitanyaenr** [comment]
Tested the PR on GCP, it works as expected. The worker nodes got distributed across the available 4 zones.

**Comment by chaitanyaenr** [comment]
@akrzos we can merge it once you test it on AWS and Azure.

**Comment by akrzos** [comment]
> @akrzos we can merge it once you test it on AWS and Azure.

Ran fine with both my azure and aws environment

**Pull request merged**
